
[functions.admin-create-user]
enabled = true
verify_jwt = true
import_map = "./functions/admin-create-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-create-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-create-user/*.html" ]

[functions.send-whatsapp-manual]
enabled = true
verify_jwt = true
import_map = "./functions/send-whatsapp-manual/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-whatsapp-manual/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-whatsapp-manual/*.html" ]
